#pragma once
#ifndef GRID_COMPOSER_PRIVATE_H
#define GRID_COMPOSER_PRIVATE_H

#ifdef __cplusplus
extern "C" {
#endif

#define GRID_COMPOSER_DRAW_QUEUE_MAX_ITEMS 10U
#define GRID_COMPOSER_DRAW_MAX_UPDATE_RATE 10U

#define GRID_COMPOSER_DRAW_TASK_STACK       6144U
#define GRID_COMPOSER_DRAW_TASK_PRIO        20U
#define GRID_COMPOSER_DRAW_TASK_CORE        0U
#define GRID_COMPOSER_DRAW_TASK_UPDATE_RATE 60U

#define GRID_COMPOSER_CELL_MAX_ROWS 1U
#define GRID_COMPOSER_CELL_MAX_COLS 3U

#ifdef __cplusplus
}
#endif
#endif