version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8888:8888
    volumes:
      - /home/shtuk/docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/shtuk/docker-compose/nginx/certs:/etc/nginx/certs

networks:
 nginx-net:
    driver: nginx-net